In [1]:
import pandas as pd

In [2]:
var = ['date','tweet']
df1 = pd.read_csv("thomascup_090522.csv", names=var)
df2 = pd.read_csv("thomascup_100522.csv", names=var)
df3 = pd.read_csv("thomascup_110522.csv", names=var)
df4 = pd.read_csv("thomascup_120522.csv", names=var)
df5 = pd.read_csv("thomascup_130522.csv", names=var)
df6 = pd.read_csv("thomascup_140522.csv", names=var)
df7 = pd.read_csv("thomascup_150522.csv", names=var)
df8 = pd.read_csv("thomascup_160522.csv", names=var)
df9 = pd.read_csv("thomascup_170522.csv", names=var)

In [3]:
df_list = [df1, df2, df3, df4, df5, df6, df7, df8, df9]

In [4]:
df_list

[                         date  \
 0   2022-05-09 23:59:37+00:00
 1   2022-05-09 23:59:07+00:00
 2   2022-05-09 23:58:04+00:00
 3   2022-05-09 23:57:46+00:00
 4   2022-05-09 23:56:48+00:00
 ..                        ...
 95  2022-05-09 23:23:50+00:00
 96  2022-05-09 23:23:35+00:00
 97  2022-05-09 23:22:30+00:00
 98  2022-05-09 23:22:16+00:00
 99  2022-05-09 23:21:32+00:00

                                                 tweet
 0   Weh gue gatau kalo td malem fadil jaidi storii...
 1   TotalEnergies BWF Thomas and Uber Cup Finals 2...
 2   Setiap ada Thomas Cup dan Uber. Kenapa WADA se...
 3   TotalEnergies BWF Thomas and Uber Cup Finals 2...
 4   Kalo ada yg pengen banding"in Christie sama Gi...
 ..                                                ...
 95  TotalEnergies BWF Thomas and Uber Cup Finals 2...
 96  Kevin/Bagas Menang, Indonesia ke Perempat Fina...
 97  Jia underperformed lepas Thomas cup tahun lepa...
 98  Kurang tidur ini salah siapa? Ya jelas Thomas cup
 99  Kevin/Bagas Menang, Indonesia ke Perempat Fina...

 [100 rows x 2 columns],                          date  \
 0   2022-05-10 23:59:42+00:00
 1   2022-05-10 23:57:59+00:00
 2   2022-05-10 23:53:15+00:00
 3   2022-05-10 23:53:10+00:00
 4   2022-05-10 23:47:01+00:00
 ..                        ...
 95  2022-05-10 17:17:44+00:00
 96  2022-05-10 17:14:50+00:00
 97  2022-05-10 17:13:48+00:00
 98  2022-05-10 17:08:37+00:00
 99  2022-05-10 17:06:04+00:00

                                                 tweet
 0   ‚ö†Ô∏è Kalau lu orang nak Malaysia team menang sam...
 1   @Namibia_baru @simplepipel @BadmintonTalk Iya ...
 2   ‚ö†Ô∏è Kalau lu orang nak Malaysia team menang sam...
 3   Thomas Cup 2022: 8 Negara Lolos ke Perempat Fi...
 4   ‚ö†Ô∏è Kalau lu orang nak Malaysia team menang sam...
 ..                                                ...
 95  #BWF | Sanggupkah  üáÆüá©Fajar Alfian dan üáÆüá©Muhamm...
 96  ‚ö†Ô∏è Kalau lu orang nak Malaysia team menang sam...
 97  ‚ö†Ô∏è Kalau lu orang nak Malaysia team menang sam...
 98  dikabarkan anggota grup B, C, dan D thomas cup...
 99  ‚ö†Ô∏è Kalau lu orang nak Malaysia team menang sam...

 [100 rows x 2 columns],                          date  \
 0   2022-05-11 23:59:46+00:00
 1   2022-05-11 23:59:43+00:00
 2   2022-05-11 23:59:36+00:00
 3   2022-05-11 23:59:32+00:00
 4   2022-05-11 23:59:09+00:00
 ..                        ...
 95  2022-05-11 23:29:07+00:00
 96  2022-05-11 23:28:45+00:00
 97  2022-05-11 23:28:14+00:00
 98  2022-05-11 23:27:44+00:00
 99  2022-05-11 23:27:39+00:00

                                                 tweet
 0   ginting dah prediksiin bakal 2-2 ye bundüôÉ\r\n\...
 1   Agak kasian sama tim Thomas Cup nya Jepang yan...
 2   Mari kita mengulang final thomas cup thn lalu ...
 3   Appreciation Post\r\n\r\nGame 1: Tertinggal 6-...
 4   Pesan saya untuk memacu motivasi Syabda untuk ...
 ..                                                ...
 95  Dah gila thomas cup aku ni agaknya. Kalah upda...
 96  Agak kasian sama tim Thomas Cup nya Jepang yan...
 97  Med Predict Thomas Cup 2022\r\n\r\nQuarter Fin...
 98  Thomas cup pertama saya udah habis. Besok akan...
 99           Ya Allahhhhh thomas cup ngeri banget....

 [100 rows x 2 columns],                          date  \
 0   2022-05-12 23:59:51+00:00
 1   2022-05-12 23:59:38+00:00
 2   2022-05-12 23:59:29+00:00
 3   2022-05-12 23:59:18+00:00
 4   2022-05-12 23:59:06+00:00
 ..                        ...
 95  2022-05-12 23:39:12+00:00
 96  2022-05-12 23:39:00+00:00
 97  2022-05-12 23:38:54+00:00
 98  2022-05-12 23:38:36+00:00
 99  2022-05-12 23:38:27+00:00

                                                 tweet
 0   Analisis Thomas Cup 2022\r\n\r\n1. Ramalan Zii...
 1   Bener bener copy paste\r\nDaGing = Syabda Gint...
 2   Piala Thomas 2022\r\n\r\nTim Thomas Cup Indone...
 3   Di 2 edisi Thomas Cup terakhir, tembok besar C...
 4   Cuma satu benda aku tak puas hati ialah\r\n\r\...
 ..                                                ...
 95  Top 3 Sports: Indonesia ke Semifinal Thomas Cu...
 96  Bener bener copy paste\r\nDaGing = Syabda Gint...
 97  Di 2 edisi Thomas Cup terakhir, tembok besar C...
 98  Jonatan Mengaku Ditolong Ginting dan Kevin/Ahs...
 99  @peromight__ @BadmintonTalk Wajar ya ini sekel...

 [100 rows x 2 columns],                          date  \
 0   2022-05-13 23:59:31+00:00
 1   2022-05-13 23:59:30+00:00
 2   2022-05-13 23:59:29+00:00
 3   2022-05-13 23:59:20+00:00
 4   2022-05-13 23:59:09+00:00
 ..                        ...
 95  2022-05-13 23:39:02+00:00
 96  2022-05-13 23:38:55+00:00
 97  2022-05-13 23:38:47+00:00
 98  2022-05-13 23:38:27+00:00
 99  2022-05-13 23:38:22+00:00

                                                 tweet
 0   Tiba tiba aku rasa team Thomas Cup IND ni mcm ...
 1   Tapi bukan berarti kekalahan Jona &amp; FajRi ...
 2   Besok mau staycation agendanya nonton final th...
 3   BEGADANG GUE GA SIA2. IN VITO WE TRUST! KITA K...
 4   Sejarah untuk India bisa ke final Thomas cup s...
 ..                                                ...
 95  Prannoy H.S membawa India untuk pertama kali m...
 96  apa yang aku nak : Indonesia menang lagi Thoma...
 97  15 MEI 2022 - FINAL #ThomasCup2022 \r\n\r\nIND...
 98  Ini kalo ada BL yang baru join pas Thomas-Uber...
 99  FINAL THOMAS CUP INA VS IND, kalo kata ci agne...

 [100 rows x 2 columns],                          date  \
 0   2022-05-14 23:59:56+00:00
 1   2022-05-14 23:59:44+00:00
 2   2022-05-14 23:59:28+00:00
 3   2022-05-14 23:59:20+00:00
 4   2022-05-14 23:59:10+00:00
 ..                        ...
 95  2022-05-14 23:10:18+00:00
 96  2022-05-14 23:09:38+00:00
 97  2022-05-14 23:09:00+00:00
 98  2022-05-14 23:08:48+00:00
 99  2022-05-14 23:04:58+00:00

                                                 tweet
 0   semangat tim thomas cup buat finalnya hari ini...
 1                         Hari ini Final Thomas Cup ‚ú®
 2   Fantastis, ini Nilai Bonus Thomas Cup 2022 Jik...
 3   final thomas cup nanti kalau BL IND ajak gaduh...
 4   @akulahgemini Kuy. Yang menang bisa ikut Thoma...
 ..                                                ...
 95  Uber cup boleh berdarah-darah, tapi tolong yaa...
 96  Indonesia paling sering tampil di final Thomas...
 97  Uber cup boleh berdarah-darah, tapi tolong yaa...
 98  Thomas Tuchel:\r\n\r\n"Seperti di final terakh...
 99          Semoga bisa liat final thomas cup, Aamiin

 [100 rows x 2 columns],                          date  \
 0   2022-05-15 23:59:44+00:00
 1   2022-05-15 23:59:21+00:00
 2   2022-05-15 23:59:08+00:00
 3   2022-05-15 23:59:07+00:00
 4   2022-05-15 23:58:21+00:00
 ..                        ...
 95  2022-05-15 23:28:26+00:00
 96  2022-05-15 23:28:16+00:00
 97  2022-05-15 23:27:21+00:00
 98  2022-05-15 23:27:11+00:00
 99  2022-05-15 23:27:09+00:00

                                                 tweet
 0   Berhubung saya bl baru, barusan ngulik2 wikipe...
 1   kalau kalian liat ada orang yang diem, murung,...
 2   Tahun lalu nyesek di Sudirman Cup, menang di T...
 3   Ada masanya setelah Indonesia jd Juara Thomas ...
 4   @BadmintonTalk SELAMAT BUAT INDIA KALIAN PANTA...
 ..                                                ...
 95  Tahun lalu nyesek di Sudirman Cup, menang di T...
 96  Berhubung saya bl baru, barusan ngulik2 wikipe...
 97  Ginting, Jonatan dan Kevin terhitung sudah 3x ...
 98  Thomas cup pertama saya udah habis. Besok akan...
 99  @BadmintonTalk Bangun tidur pun masih berasa n...

 [100 rows x 2 columns],                          date  \
 0   2022-05-16 23:59:22+00:00
 1   2022-05-16 23:59:04+00:00
 2   2022-05-16 23:56:33+00:00
 3   2022-05-16 23:55:29+00:00
 4   2022-05-16 23:52:20+00:00
 ..                        ...
 95  2022-05-16 17:34:35+00:00
 96  2022-05-16 17:33:57+00:00
 97  2022-05-16 17:33:11+00:00
 98  2022-05-16 17:32:54+00:00
 99  2022-05-16 17:32:52+00:00

                                                 tweet
 0   Kelihatannya Hendra /Ahsan sdh percaya dgn MD ...
 1   Ginting telah bermain selama 408 menit selama ...
 2   Udh ngelupain sedihnya thomas cup, sekarang wa...
 3   Udh ngelupain sedihnya thomas cup, sekarang wa...
 4   TIM THOMAS INDONESIA ME;LAJU KE FINAL THOMAS C...
 ..                                                ...
 95  @Mayfrientha @sbtmskn Hahaha kayanya siy boro2...
 96  Berikut prediksi ranking Versi Team #Bhulukhud...
 97  Berikut prediksi ranking Versi Team #Bhulukhud...
 98  Ada masanya setelah Indonesia jd Juara Thomas ...
 99  Berikut prediksi ranking Versi Team #Bhulukhud...

 [100 rows x 2 columns],                          date  \
 0   2022-05-17 13:18:31+00:00
 1   2022-05-17 13:18:21+00:00
 2   2022-05-17 13:18:21+00:00
 3   2022-05-17 13:18:19+00:00
 4   2022-05-17 13:18:06+00:00
 ..                        ...
 95  2022-05-17 13:02:46+00:00
 96  2022-05-17 13:02:36+00:00
 97  2022-05-17 13:02:35+00:00
 98  2022-05-17 13:02:19+00:00
 99  2022-05-17 13:02:13+00:00

                                                 tweet
 0   Kita harap kuih lapis masuk sea games untuk ti...
 1   btw ges banyak sejarah baru tahun ini mah dari...
 2   Lagi 4-6 tahun we might see this squad in Thom...
 3   @badminton__fess BATC Putra ‚ùå\r\nThomas Cup ‚ùå\...
 4   Lagi 4-6 tahun we might see this squad in Thom...
 ..                                                ...
 95  Belum sembuh potek Thomas Cup kemarin, dilanju...
 96  btw ges banyak sejarah baru tahun ini mah dari...
 97  Belum sembuh potek Thomas Cup kemarin, dilanju...
 98  Lagi 4-6 tahun we might see this squad in Thom...
 99  @TeamMsia Even tk dpt thomas cup harap bleh dp...

 [100 rows x 2 columns]]

In [5]:
gabungan = pd.concat(df_list, ignore_index=True, axis=0)

In [6]:
gabungan.head()

,date,tweet
0,2022-05-09 23:59:37+00:00,Weh gue gatau kalo td malem fadil jaidi storii...
1,2022-05-09 23:59:07+00:00,TotalEnergies BWF Thomas and Uber Cup Finals 2...
2,2022-05-09 23:58:04+00:00,Setiap ada Thomas Cup dan Uber. Kenapa WADA se...
3,2022-05-09 23:57:46+00:00,TotalEnergies BWF Thomas and Uber Cup Finals 2...
4,2022-05-09 23:56:48+00:00,"Kalo ada yg pengen banding""in Christie sama Gi..."

In [7]:
#pilih data yang ingin digunakan saja
df  = pd.DataFrame(gabungan['tweet'])
df

                                                 tweet
0    Weh gue gatau kalo td malem fadil jaidi storii...
1    TotalEnergies BWF Thomas and Uber Cup Finals 2...
2    Setiap ada Thomas Cup dan Uber. Kenapa WADA se...
3    TotalEnergies BWF Thomas and Uber Cup Finals 2...
4    Kalo ada yg pengen banding"in Christie sama Gi...
..                                                 ...
895  Belum sembuh potek Thomas Cup kemarin, dilanju...
896  btw ges banyak sejarah baru tahun ini mah dari...
897  Belum sembuh potek Thomas Cup kemarin, dilanju...
898  Lagi 4-6 tahun we might see this squad in Thom...
899  @TeamMsia Even tk dpt thomas cup harap bleh dp...

[900 rows x 1 columns]

In [8]:
import pandas as pd
import numpy as np
import re
#remove user
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
    return input_txt    
df['remove_user'] = np.vectorize(remove_pattern)(df['tweet'], "@[\w]*")
df.drop_duplicates(subset ="remove_user", keep = 'first', inplace = True)
df.sort_values("remove_user", inplace = True)

In [9]:
df.head()

,tweet,remove_user
707,@Hicapna_ @bhulukhuduktv @INABadminton @bwfmed...,Makanya pengen tau ranking mereka pasc...
627,@sumitsaurabh @srikidambi @lakshya_sen @satwik...,Bravo India . #ThomasCup winners 2022.\r...
894,@dikidiew @choli274 @nachos_tachos @BadmintonT...,"Benar, Lee Chong Wei sendiri pun ga pernah..."
791,@tarararar1 @onyourare @mrivaldi__ @BadmintonT...,Betul udh gk ada benernya dimata dia. Jadi...
101,@Namibia_baru @simplepipel @BadmintonTalk Iya ...,Iya benar. Zelin Resiana ex WD yg juara Ube...

In [13]:
data_labeling = df['remove_user']
data_labeling.to_csv("thomascup_gabungan.csv",encoding='utf-8', index=False)

In [14]:
#load dataset
labeling_df = pd.read_csv('thomascup_gabungan.csv')
labeling_df.head()

                                         remove_user
0          Makanya pengen tau ranking mereka pasc...
1        Bravo India . #ThomasCup winners 2022.\r...
2      Benar, Lee Chong Wei sendiri pun ga pernah...
3      Betul udh gk ada benernya dimata dia. Jadi...
4     Iya benar. Zelin Resiana ex WD yg juara Ube...